### ISSUE TITLE
Incorrect "changed SONAME" warning

### ISSUE THREAD

**Issue by ajdavis** [lvc/abi-tracker#6]
This page compares the libmongoc version 1.4.2 ABI with the current version https://github.com/mongodb/mongo-c-driver/commit/c5d211e040210c0b476f7206cddd2b5c9e87eb51:

![image](https://cloud.githubusercontent.com/assets/84101/19557979/f7766770-9695-11e6-8f43-d46bfbfd79a3.png)

https://abi-laboratory.pro/tracker/objects_report/mongo-c-driver/1.4.2/current/report.html

We haven't changed our SONAME, it was "libmongoc-1.0.so.0" in 1.4.2 as well as in the current HEAD. (I just rebuilt 1.4.2 to confirm.)

Thanks!

**Comment by lvc** [comment]
Hello,

The issue is that the current HEAD is built by Autotools (`sh ./autogen.sh; sh ./configure ...`). But 1.4.x are built by CMake. Seems that SONAMEs are different in this cases.

Fixed the tracker to build current HEAD by CMake.

The report is updated: https://abi-laboratory.pro/tracker/timeline/mongo-c-driver/

Also added 1.5.0-rc3 to the report.

Thank you.

**Comment by ajdavis** [comment]
Interesting, thanks. Might be a problem with our CMake configuration then, I'll investigate: [CDRIVER-1870](https://jira.mongodb.org/browse/CDRIVER-1870).
